/* Original AutoType sentence expansion. Shared with server challenge catalog. */
window.AutoTypeContentPack=Object.freeze({
 standard:Object.freeze([
  "the little robot misplaced its favorite screwdriver",
  "we found a paper map inside the dusty piano",
  "the baker decorated a cake shaped like a planet",
  "a silver kite spun above the empty soccer field",
  "the museum opened a secret room for the weekend",
  "my headphones played the wrong song at full volume",
  "someone built a tiny bridge across the puddle",
  "the librarian discovered a bookmark from another century",
  "our class invented a game with impossible rules",
  "a bright meteor appeared just before the sunrise",
  "the delivery drone circled the house three times",
  "we painted a mural beside the community garden",
  "the aquarium lights turned purple during the tour",
  "her notebook contained sketches of unusual machines",
  "the vending machine offered a mysterious new flavor",
  "a friendly fox watched us from the hillside",
  "the arcade announced a surprise championship after lunch",
  "our telescope revealed a distant orange planet",
  "the old suitcase contained postcards from fifty cities",
  "the science fair featured a talking cardboard dinosaur",
  "a skateboard rolled across the basketball court alone",
  "the little bakery smelled like cinnamon and vanilla",
  "we discovered a quiet rooftop above the theater",
  "the glowing sign flickered whenever the train passed",
  "our group designed a maze for the robotics club",
  "the storm left tiny crystals on every railing",
  "his puzzle box contained twelve hidden compartments",
  "an owl landed silently on the garden fence",
  "the orchestra practiced beneath a painted wooden ceiling",
  "every window reflected the fireworks differently tonight",
  "the computer lab hosted a midnight coding marathon",
  "she found an old photograph behind the bookshelf",
  "a curious pigeon followed us through the plaza",
  "the newest update turned ordinary buttons into stars",
  "the neighborhood festival featured gigantic paper lanterns",
  "we found an abandoned chessboard near the fountain",
  "someone left a miniature spaceship on the teacher desk",
  "the cloudy sky finally cleared above the mountains",
  "his invention sorted socks by their favorite colors",
  "the picnic ended when the sprinklers suddenly started",
  "the little boat traveled beneath the stone bridge",
  "our band rehearsed inside a crowded garage",
  "the coffee cup balanced beside a precarious stack",
  "the weather station recorded an unusually warm morning",
  "a stray balloon floated into the open classroom",
  "the train conductor waved at a familiar passenger",
  "we spent the afternoon exploring a digital museum",
  "the scoreboard displayed an impossible number for a moment",
  "a garden snail crossed the path after rainfall",
  "the new game mode confused even the experienced testers",
  "our school newspaper published an unexpected front page",
  "the midnight train arrived beneath a violet sky",
  "a talented artist painted stars on recycled cardboard",
  "the vending machine hummed louder than the nearby refrigerator",
  "our professor brought a strange compass to class",
  "the old projector displayed an upside down photograph",
  "someone arranged tiny toy cars around the fountain",
  "the chess tournament finished with a surprising final move",
  "the music studio echoed with a cheerful melody",
  "the aquarium tunnel made the sharks appear to float",
  "a quiet cat settled beneath the gaming chair",
  "the community garden grew enormous yellow sunflowers",
  "we built a tiny weather balloon from paper",
  "the coffee shop displayed drawings from local students",
  "his phone suggested a route through the park",
  "an enthusiastic volunteer guided everyone toward the library",
  "the laser printer left colorful marks on the paper",
  "a hidden stairway led to the observatory balcony",
  "the delivery arrived inside a bright orange package",
  "the wooden bridge creaked beneath the morning runners",
  "a wildflower grew through the cracks in the sidewalk",
  "the team celebrated after solving the last puzzle",
  "the festival lights formed shapes across the harbor",
  "an unexpected rainbow appeared behind the science center",
  "the little dog guarded a squeaky rubber duck",
  "we followed the chalk arrows toward the art room",
  "the train station clock stopped at midnight",
  "a tiny telescope pointed toward the brightest constellation",
  "the baker accidentally invented a delicious new pastry",
  "someone built a miniature city from wooden blocks",
  "our friends played board games during the thunderstorm",
  "the robot vacuum became stuck beneath the sofa",
  "the old radio played music from another decade",
  "the library opened an exhibition of handmade maps",
  "every keyboard sounded different in the rehearsal room",
  "the sunny afternoon became perfect for kite flying",
  "a bright blue butterfly rested on the fence",
  "our experiment revealed a surprising pattern in the numbers",
  "the puzzle pieces formed an unexpected landscape",
  "the mountain trail ended beside a peaceful waterfall",
  "the neighborhood cinema hosted a costume contest",
  "the robotics team programmed a machine to draw flowers",
  "our garden attracted colorful birds throughout the summer",
  "the science teacher demonstrated a floating paperclip trick",
  "a handwritten sign pointed toward the hidden courtyard",
  "the subway tunnel echoed with distant footsteps",
  "the game narrator completely misunderstood the final challenge",
  "a flock of birds crossed the bright moon",
  "we built a cardboard fort beside the living room",
  "the digital clock changed colors every ten minutes",
  "the wooden floor creaked after the music stopped",
  "the skate park hosted its first evening competition",
  "our team drew a map of imaginary islands",
  "the scoreboard blinked as the final timer expired",
  "the park ranger spotted fresh tracks beside the creek",
  "the theater curtains opened earlier than anyone expected",
  "a colorful paper crane rested on the windowsill",
  "the newest gadget included a surprisingly useful flashlight",
  "our classroom designed posters for the school festival",
  "the astronomy club searched for a new comet before the final bell rang",
  "the astronomy club searched for a new comet during the quiet afternoon",
  "our friends organized a secret puzzle tournament while everyone watched in amazement",
  "our friends organized a secret puzzle tournament after the unexpected announcement",
  "the sleepy hamster explored its cardboard castle just as the lights began to flicker",
  "the sleepy hamster explored its cardboard castle before the entire room burst into laughter",
  "a young inventor tested a pocket sized robot during the quiet afternoon",
  "a young inventor tested a pocket sized robot as the crowd started cheering",
  "the art teacher painted a strange landscape after the unexpected announcement",
  "the art teacher painted a strange landscape while the rain tapped the windows",
  "the neighborhood team practiced a creative strategy before the entire room burst into laughter",
  "the neighborhood team practiced a creative strategy before the final bell rang",
  "the bus driver discovered a forgotten backpack as the crowd started cheering",
  "the bus driver discovered a forgotten backpack while everyone watched in amazement",
  "a curious student decoded the mysterious note while the rain tapped the windows",
  "a curious student decoded the mysterious note just as the lights began to flicker",
  "the soccer captain planned an unusual celebration before the final bell rang",
  "the soccer captain planned an unusual celebration during the quiet afternoon",
  "our orchestra selected a difficult new song while everyone watched in amazement",
  "our orchestra selected a difficult new song after the unexpected announcement",
  "the arcade owner displayed a golden trophy just as the lights began to flicker",
  "the arcade owner displayed a golden trophy before the entire room burst into laughter",
  "the library volunteer arranged colorful book covers during the quiet afternoon",
  "the library volunteer arranged colorful book covers as the crowd started cheering",
  "a talented chef invented a spicy sandwich after the unexpected announcement",
  "a talented chef invented a spicy sandwich while the rain tapped the windows",
  "the science team launched a tiny rocket before the entire room burst into laughter",
  "the science team launched a tiny rocket before the final bell rang",
  "the computer club designed a complicated challenge as the crowd started cheering",
  "the computer club designed a complicated challenge while everyone watched in amazement",
  "the photographer waited for a dramatic sunset while the rain tapped the windows",
  "the photographer waited for a dramatic sunset just as the lights began to flicker",
  "the garden club planted bright purple flowers before the final bell rang",
  "the garden club planted bright purple flowers during the quiet afternoon",
  "a friendly astronaut described an imaginary planet while everyone watched in amazement",
  "a friendly astronaut described an imaginary planet after the unexpected announcement",
  "the museum guide shared a surprising story just as the lights began to flicker",
  "the museum guide shared a surprising story before the entire room burst into laughter",
  "our robotics team solved a stubborn problem during the quiet afternoon",
  "our robotics team solved a stubborn problem as the crowd started cheering",
  "the chess player considered one final move after the unexpected announcement",
  "the chess player considered one final move while the rain tapped the windows",
  "the skateboard champion practiced a new trick before the entire room burst into laughter",
  "the skateboard champion practiced a new trick before the final bell rang",
  "an adventurous explorer mapped a hidden valley as the crowd started cheering",
  "an adventurous explorer mapped a hidden valley while everyone watched in amazement",
  "the musician borrowed an unusual instrument while the rain tapped the windows",
  "the musician borrowed an unusual instrument just as the lights began to flicker",
  "the baker prepared an enormous birthday cake before the final bell rang",
  "the baker prepared an enormous birthday cake during the quiet afternoon",
  "the teacher introduced a strange new assignment while everyone watched in amazement",
  "the teacher introduced a strange new assignment after the unexpected announcement",
  "the neighborhood artist finished a vibrant mural just as the lights began to flicker",
  "the neighborhood artist finished a vibrant mural before the entire room burst into laughter",
  "the game designer tested a confusing new level during the quiet afternoon",
  "the game designer tested a confusing new level as the crowd started cheering",
  "our study group discovered a helpful shortcut after the unexpected announcement",
  "our study group discovered a helpful shortcut while the rain tapped the windows",
  "the aquarium caretaker prepared a special exhibit before the entire room burst into laughter",
  "the aquarium caretaker prepared a special exhibit before the final bell rang",
  "the mountain guide suggested a quieter trail as the crowd started cheering",
  "the mountain guide suggested a quieter trail while everyone watched in amazement",
  "the little bookstore arranged its rare editions while the rain tapped the windows",
  "the little bookstore arranged its rare editions just as the lights began to flicker",
  "a creative engineer built a tiny windmill before the final bell rang",
  "a creative engineer built a tiny windmill during the quiet afternoon",
  "the drama club rehearsed a hilarious scene while everyone watched in amazement",
  "the drama club rehearsed a hilarious scene after the unexpected announcement",
  "the historian examined a faded old postcard just as the lights began to flicker",
  "the historian examined a faded old postcard before the entire room burst into laughter",
  "the football coach invented a new warmup game during the quiet afternoon",
  "the football coach invented a new warmup game as the crowd started cheering",
  "a patient detective solved the missing cookie mystery after the unexpected announcement",
  "a patient detective solved the missing cookie mystery while the rain tapped the windows",
  "the neighborhood mechanic repaired an ancient bicycle before the entire room burst into laughter",
  "the neighborhood mechanic repaired an ancient bicycle before the final bell rang",
  "the music teacher tuned a vintage guitar as the crowd started cheering",
  "the music teacher tuned a vintage guitar while everyone watched in amazement",
  "the wildlife photographer followed a colorful butterfly while the rain tapped the windows",
  "the wildlife photographer followed a colorful butterfly just as the lights began to flicker",
  "our little robot learned a surprising new trick before the final bell rang",
  "our little robot learned a surprising new trick during the quiet afternoon",
  "the science museum introduced a new exhibit while everyone watched in amazement",
  "the science museum introduced a new exhibit after the unexpected announcement",
  "the racing team tested a colorful helmet just as the lights began to flicker",
  "the racing team tested a colorful helmet before the entire room burst into laughter",
  "a curious kitten discovered an open suitcase during the quiet afternoon",
  "a curious kitten discovered an open suitcase as the crowd started cheering",
  "the newspaper editor spotted a hidden mistake after the unexpected announcement",
  "the newspaper editor spotted a hidden mistake while the rain tapped the windows",
  "the school gardener built a wooden flower box before the entire room burst into laughter",
  "the school gardener built a wooden flower box before the final bell rang",
  "the digital artist created a glowing spaceship as the crowd started cheering",
  "the digital artist created a glowing spaceship while everyone watched in amazement",
  "the basketball team practiced an unusual pass while the rain tapped the windows",
  "the basketball team practiced an unusual pass just as the lights began to flicker",
  "the weather reporter spotted distant storm clouds before the final bell rang",
  "the weather reporter spotted distant storm clouds during the quiet afternoon",
  "the new student learned a difficult magic trick while everyone watched in amazement",
  "the new student learned a difficult magic trick after the unexpected announcement"
]),
 evil:Object.freeze([
  "bro typed one letter and got a vegetable instead",
  "the predictor really chose banana during the space mission",
  "my keyboard thinks every mystery begins with a sandwich",
  "the robot insisted that spaghetti was the answer",
  "why did the autocomplete suggest pineapple again today",
  "that little guess went completely sideways in seconds",
  "the entire lobby laughed at the unexpected word",
  "the algorithm picked a potato during the final round",
  "our team was confident until the predictor chose waffle",
  "the last word somehow turned into a dancing penguin",
  "the keyboard entered chaos mode without warning anyone",
  "bro wanted victory and received a virtual pancake",
  "the game guessed glitter when the clue was gravity",
  "our friend called that prediction a spectacular plot twist",
  "even the scoreboard looked confused by that answer",
  "the autocomplete offered a cactus in the middle of space",
  "this keyboard might secretly be a confused parrot",
  "someone asked for pizza and got an imaginary planet",
  "the predictor started inventing names for every toaster",
  "the final guess turned into a dramatic rubber duck",
  "bro thought the secret word was always banana",
  "the chatbot wrote waffle instead of waterfall",
  "one random syllable sent the whole lobby laughing",
  "the computer chose jellybeans before choosing anything useful",
  "the assistant confused the garden with a spaceship",
  "our leaderboard somehow awarded points to a pineapple",
  "the keyboard decided every sentence needed more waffles",
  "this level felt like solving a riddle underwater",
  "the prediction turned a sleepy kitten into a legend",
  "the whole strategy failed because of one strange word"
]),
 words:Object.freeze([
  "acorn",
  "adventure",
  "astronaut",
  "autumn",
  "bakery",
  "balloon",
  "bamboo",
  "bicycle",
  "binoculars",
  "blueprint",
  "bookshelf",
  "breeze",
  "bridge",
  "broccoli",
  "butterfly",
  "cabin",
  "calendar",
  "canyon",
  "castle",
  "chalk",
  "chess",
  "chimney",
  "cinnamon",
  "circuit",
  "classroom",
  "clouds",
  "comet",
  "compass",
  "coral",
  "courtyard",
  "crystal",
  "cupcake",
  "desert",
  "dinosaur",
  "dragonfly",
  "drawing",
  "eclipse",
  "engine",
  "envelope",
  "experiment",
  "festival",
  "firefly",
  "flashlight",
  "fountain",
  "galaxy",
  "garden",
  "gemstone",
  "glacier",
  "guitar",
  "harbor",
  "harmony",
  "horizon",
  "hummingbird",
  "island",
  "jasmine",
  "jellybean",
  "jungle",
  "lantern",
  "laptop",
  "lighthouse",
  "library",
  "marble",
  "meadow",
  "melody",
  "meteor",
  "microscope",
  "midnight",
  "mountain",
  "museum",
  "notebook",
  "ocean",
  "orchard",
  "origami",
  "pancake",
  "parachute",
  "penguin",
  "pineapple",
  "pixel",
  "planet",
  "poster",
  "puzzle",
  "rainbow",
  "robot",
  "rocket",
  "rooftop",
  "sandwich",
  "satellite",
  "scooter",
  "shoreline",
  "skateboard",
  "snowfall",
  "solar",
  "spaceship",
  "sparkle",
  "stadium",
  "station",
  "sunset",
  "telescope",
  "theater",
  "thunder",
  "ticket",
  "treasure",
  "tunnel",
  "umbrella",
  "universe",
  "waterfall",
  "weather",
  "workshop",
  "xylophone",
  "yogurt",
  "zucchini",
  "waffle",
  "sunflower",
  "sneakers",
  "pixelated",
  "labyrinth",
  "karaoke",
  "hammock",
  "marshmallow",
  "popcorn",
  "constellation",
  "velocity",
  "gradient",
  "prism",
  "scribble",
  "mosaic",
  "radiant",
  "curious",
  "playful",
  "enormous",
  "puzzled",
  "brilliant",
  "unexpected",
  "puzzling",
  "peculiar",
  "whimsical",
  "satisfying",
  "orbiting",
  "fragrant",
  "adventurous",
  "rhythm",
  "summit",
  "bookstore",
  "backpack",
  "graffiti",
  "animation",
  "orchestra",
  "detective",
  "clockwork",
  "caramel",
  "raspberry",
  "daisy",
  "hologram",
  "arcade"
])
});
