-- Server-issued competitive round challenges.

create table if not exists public.challenge_sentences (
  id bigint generated by default as identity primary key,
  target_text text not null unique,
  pool text not null check(pool in ('standard','evil')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);
alter table public.challenge_sentences enable row level security;
drop policy if exists "challenge sentences client deny" on public.challenge_sentences;
create policy "challenge sentences client deny"
on public.challenge_sentences for all to anon,authenticated
using(false) with check(false);
grant select,insert,update,delete on public.challenge_sentences to service_role;

insert into public.challenge_sentences(target_text,pool)
values
('the moon looked bright over the quiet city','standard'),
('we found a tiny note under the old table','standard'),
('my friend brought fresh coffee before class today','standard'),
('the rain made every street shine at night','standard'),
('people often remember how a moment made them feel','standard'),
('she left her blue jacket beside the front door','standard'),
('a good idea can start with one strange question','standard'),
('the last train arrived just after midnight','standard'),
('small choices can change the shape of a day','standard'),
('he opened the window and heard birds outside','standard'),
('our team finished the project before lunch','standard'),
('the little dog waited patiently by the gate','standard'),
('music from the next room filled the hallway','standard'),
('today feels like the start of something new','standard'),
('the teacher wrote three examples on the board','standard'),
('we took the long road home after dinner','standard'),
('every player gets one chance to solve the puzzle','standard'),
('the computer guessed the wrong word again','standard'),
('a warm light glowed through the kitchen window','standard'),
('sometimes the simplest answer is the best one','standard'),
('the elevator stopped one floor before anyone expected','standard'),
('someone left a skateboard beside the library entrance','standard'),
('the morning bus arrived while everyone was still talking','standard'),
('a red balloon drifted slowly above the crowded park','standard'),
('the battery died right before the final level loaded','standard'),
('we ordered noodles and watched the storm from inside','standard'),
('the hallway lights flickered once and then stayed dark','standard'),
('she changed the playlist when the next song started','standard'),
('his backpack somehow ended up under the wrong desk','standard'),
('the vending machine returned every coin except one','standard'),
('our group found a shortcut through the science building','standard'),
('the cat ignored everyone until somebody opened a snack','standard'),
('three notifications appeared before the phone finished charging','standard'),
('the keyboard sounded louder in the empty computer lab','standard'),
('we missed the exit and discovered a better route','standard'),
('the scoreboard changed during the final few seconds','standard'),
('a paper airplane landed perfectly inside the open box','standard'),
('the train doors closed before my friend reached them','standard'),
('someone drew a tiny face on the whiteboard marker','standard'),
('the new update moved every button to a strange place','standard'),
('we stayed outside until the streetlights finally turned on','standard'),
('the cafeteria line wrapped around the corner at noon','standard'),
('her headphones disconnected in the middle of the chorus','standard'),
('the old camera made every photo look strangely cinematic','standard'),
('a random idea became the best part of the project','standard'),
('the printer decided to jam five minutes before class','standard'),
('our code worked perfectly until somebody touched one line','standard'),
('the window reflected the city like a second skyline','standard'),
('he forgot the password immediately after changing it','standard'),
('the controller vibrated before anything appeared on screen','standard'),
('we found an empty table right beside the window','standard'),
('the game loaded faster after the second restart','standard'),
('a single typo changed the meaning of the entire message','standard'),
('the coffee shop was quieter than usual that afternoon','standard'),
('their presentation ended exactly when the timer reached zero','standard'),
('the dog carried one shoe into the living room','standard'),
('a delivery truck blocked the street for several minutes','standard'),
('she solved the puzzle without writing anything down','standard'),
('the wind pushed every fallen leaf toward the fence','standard'),
('we could hear music from somewhere across the courtyard','standard'),
('the notification disappeared before anyone could read it','standard'),
('a tiny scratch made the screen look much worse','standard'),
('the shortcut saved time until the road suddenly closed','standard'),
('he packed everything except the charger he actually needed','standard'),
('the bright sign was visible from two blocks away','standard'),
('our table somehow became the loudest one in the room','standard'),
('the timer beeped while everyone was still getting ready','standard'),
('we compared answers and somehow got four different results','standard'),
('the chair rolled backward when he reached for the notebook','standard'),
('a message popped up saying the file was finally ready','standard'),
('the sunset turned every window orange for a few minutes','standard'),
('someone changed the group chat name again last night','standard'),
('the first attempt looked terrible but the second one worked','standard'),
('she found the missing key inside a jacket pocket','standard'),
('the website loaded differently on every browser we tried','standard'),
('a small update completely changed how the menu felt','standard'),
('the last slice disappeared before anyone claimed it','standard'),
('we watched the clouds move across the stadium lights','standard'),
('the microphone picked up a conversation from across the room','standard'),
('the screen dimmed right when the important part started','standard'),
('our teacher laughed when the example actually failed','standard'),
('the package arrived earlier than the tracking page predicted','standard'),
('he took the stairs because the elevator looked crowded','standard'),
('a notification sound made everyone check their phone','standard'),
('the hallway smelled like pizza for the entire afternoon','standard'),
('we built the prototype first and fixed the details later','standard'),
('the second question was much harder than the first','standard'),
('someone accidentally opened the wrong presentation in class','standard'),
('the cursor vanished whenever it moved over the image','standard'),
('the room became silent as soon as the video started','standard'),
('a bright sticker covered the scratch on the laptop','standard'),
('the map suggested a route that nobody wanted to take','standard'),
('we finished the assignment with exactly one minute left','standard'),
('the lights outside reflected across the wet pavement','standard'),
('the final answer looked obvious only after we solved it','standard'),
('she carried three bags and still opened the door','standard'),
('the new keyboard had a completely different sound','standard'),
('the app remembered a setting that everyone forgot changing','standard'),
('our table shook whenever somebody bumped the floor','standard'),
('the first snow melted before the afternoon was over','standard'),
('bro really thought the first guess was gonna work','evil'),
('lowkey that answer was way too obvious','evil'),
('nah the autocomplete is actually trolling right now','evil'),
('that guess was so random it almost felt personal','evil'),
('the game really said bet and guessed something else','evil'),
('this predictor has absolutely zero chill today','evil'),
('my last guess was cooked before i finished typing','evil'),
('the autocomplete keeps yapping instead of helping','evil'),
('we were locked in until the ai chose the weirdest word','evil'),
('bro picked the most cursed word possible','evil')
on conflict(target_text) do update set pool=excluded.pool,active=true;

create table if not exists public.round_challenges (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  mode text not null check(mode in ('classic','context','sentence','evil','daily','tournament')),
  target_text text not null,
  target_words integer not null check(target_words>0),
  tournament_id uuid references public.tournaments(id) on delete set null,
  daily_key date,
  status text not null default 'issued' check(status in ('issued','consumed','abandoned','expired')),
  issued_at timestamptz not null default now(),
  expires_at timestamptz not null default (now()+interval '30 minutes'),
  consumed_at timestamptz
);
create index if not exists round_challenges_user_idx on public.round_challenges(user_id,issued_at desc);
create index if not exists round_challenges_tournament_idx on public.round_challenges(tournament_id,user_id);
alter table public.round_challenges enable row level security;
drop policy if exists "round challenges readable by owner" on public.round_challenges;
create policy "round challenges readable by owner"
on public.round_challenges for select to authenticated
using((select auth.uid())=user_id);
grant select on public.round_challenges to authenticated;
grant select,insert,update,delete on public.round_challenges to service_role;

alter table public.round_results
  add column if not exists challenge_id uuid references public.round_challenges(id) on delete set null,
  add column if not exists verified boolean not null default false,
  add column if not exists server_elapsed_ms bigint;

create index if not exists round_results_verified_score_idx
on public.round_results(verified,score desc);

alter table public.player_stats
  add column if not exists verified_best_score bigint not null default 0,
  add column if not exists verified_rounds bigint not null default 0;

create or replace function public.autotype_start_round(
  p_user uuid,
  p_mode text,
  p_tournament text default null
) returns jsonb
language plpgsql security definer set search_path=public
as $$
declare
  chosen public.challenge_sentences%rowtype;
  ch public.round_challenges%rowtype;
  t public.tournaments%rowtype;
  word_count integer;
  pool_count integer;
  daily_offset integer;
begin
  if p_mode not in ('classic','context','sentence','evil','daily','tournament') then
    raise exception 'This mode does not use server challenges';
  end if;

  if (
    select count(*)
    from public.round_challenges
    where user_id=p_user and issued_at>now()-interval '5 minutes'
  ) >= 30 then
    raise exception 'Too many round starts. Try again in a few minutes.';
  end if;

  if p_mode='tournament' then
    if coalesce(trim(p_tournament),'')='' then raise exception 'Tournament is required'; end if;

    select * into t
    from public.tournaments
    where slug=p_tournament
       or (p_tournament ~* '^[0-9a-f-]{36}$' and id=p_tournament::uuid)
    limit 1;

    if t.id is null then raise exception 'Tournament not found'; end if;
    if t.status<>'running' then raise exception 'Tournament is not running'; end if;

    if not exists(
      select 1 from public.tournament_entries
      where tournament_id=t.id and user_id=p_user
        and status in ('registered','playing')
    ) then raise exception 'You are not registered for this tournament'; end if;

    if exists(
      select 1 from public.tournament_entries
      where tournament_id=t.id and user_id=p_user and score is not null
    ) then raise exception 'Your tournament attempt is already complete'; end if;

    select * into ch
    from public.round_challenges
    where user_id=p_user and tournament_id=t.id and status='issued' and expires_at>now()
    order by issued_at desc limit 1;

    if ch.id is not null then
      return jsonb_build_object(
        'challenge_id',ch.id,'mode',ch.mode,'target_text',ch.target_text,
        'expires_at',ch.expires_at,'tournament_id',ch.tournament_id
      );
    end if;
  end if;

  if p_mode='daily' then
    select * into ch
    from public.round_challenges
    where user_id=p_user and mode='daily' and daily_key=current_date
      and status='issued' and expires_at>now()
    order by issued_at desc limit 1;

    if ch.id is not null then
      return jsonb_build_object(
        'challenge_id',ch.id,'mode',ch.mode,'target_text',ch.target_text,
        'expires_at',ch.expires_at,'daily_key',ch.daily_key
      );
    end if;

    select count(*) into pool_count
    from public.challenge_sentences
    where pool='standard' and active=true;

    if pool_count=0 then raise exception 'No challenge sentences are available'; end if;

    daily_offset:=mod(
      (hashtextextended(current_date::text,0) & 9223372036854775807),
      pool_count
    )::integer;

    select * into chosen
    from public.challenge_sentences
    where pool='standard' and active=true
    order by id
    offset daily_offset limit 1;
  elsif p_mode='evil' then
    select * into chosen
    from public.challenge_sentences
    where active=true and pool in ('standard','evil')
    order by
      case when pool='evil' then random()*0.65 else random() end
    limit 1;
  else
    select * into chosen
    from public.challenge_sentences
    where pool='standard' and active=true
    order by random()
    limit 1;
  end if;

  if chosen.id is null then raise exception 'No challenge sentence is available'; end if;

  word_count:=array_length(regexp_split_to_array(trim(chosen.target_text),'\s+'),1);

  update public.round_challenges
  set status='abandoned'
  where user_id=p_user
    and status='issued'
    and expires_at>now()
    and mode=p_mode
    and (p_mode<>'tournament' or tournament_id=t.id);

  insert into public.round_challenges(
    user_id,mode,target_text,target_words,tournament_id,daily_key
  )
  values(
    p_user,p_mode,chosen.target_text,word_count,
    case when p_mode='tournament' then t.id else null end,
    case when p_mode='daily' then current_date else null end
  )
  returning * into ch;

  if p_mode='tournament' then
    update public.tournament_entries
    set status='playing'
    where tournament_id=t.id and user_id=p_user and status='registered';
  end if;

  return jsonb_build_object(
    'challenge_id',ch.id,
    'mode',ch.mode,
    'target_text',ch.target_text,
    'expires_at',ch.expires_at,
    'daily_key',ch.daily_key,
    'tournament_id',ch.tournament_id
  );
end;
$$;

revoke execute on function public.autotype_start_round(uuid,text,text) from public,anon,authenticated;
grant execute on function public.autotype_start_round(uuid,text,text) to service_role;

create or replace function public.autotype_record_verified_round(
  p_user uuid,
  p_challenge uuid,
  p_round uuid,
  p_mode text,
  p_score bigint,
  p_words integer,
  p_erased integer,
  p_max_streak integer,
  p_total_keys integer,
  p_errors integer,
  p_duration_ms integer,
  p_one_clue boolean
) returns jsonb
language plpgsql security definer set search_path=public
as $$
declare
  ch public.round_challenges%rowtype;
  s public.player_stats%rowtype;
  w public.wallets%rowtype;
  new_rounds bigint;
  new_words bigint;
  reward_coins bigint:=20;
  reward_tickets bigint:=0;
  unlocked text[]:=array[]::text[];
  ach text;
  inserted_count integer;
  max_score bigint:=0;
  i integer;
  server_elapsed bigint;
begin
  select * into ch
  from public.round_challenges
  where id=p_challenge and user_id=p_user
  for update;

  if ch.id is null then raise exception 'Round challenge not found'; end if;
  if ch.status<>'issued' then raise exception 'This round challenge is no longer active'; end if;
  if ch.expires_at<now() then
    update public.round_challenges set status='expired' where id=ch.id;
    raise exception 'This round challenge expired';
  end if;
  if ch.mode<>p_mode then raise exception 'Round mode does not match challenge'; end if;
  if ch.target_words<>p_words then raise exception 'Round word count does not match challenge'; end if;

  if exists(select 1 from public.round_results where id=p_round and user_id=p_user) then
    select * into s from public.player_stats where user_id=p_user;
    select * into w from public.wallets where user_id=p_user;
    return jsonb_build_object(
      'duplicate',true,'verified',true,'stats',to_jsonb(s),'wallet',to_jsonb(w),
      'coins_earned',0,'tickets_earned',0,'new_achievements','[]'::jsonb
    );
  end if;

  for i in 0..greatest(0,p_words-1) loop
    max_score:=max_score+120+least(i*5,30);
  end loop;

  server_elapsed:=greatest(0,(extract(epoch from (now()-ch.issued_at))*1000)::bigint);

  if p_score<0 or p_score>max_score then raise exception 'Score is outside the valid range'; end if;
  if p_words<=0 or p_words>200 then raise exception 'Invalid word count'; end if;
  if p_max_streak<0 or p_max_streak>p_words then raise exception 'Invalid streak'; end if;
  if p_total_keys<p_words*2 or p_total_keys>20000 then raise exception 'Invalid key count'; end if;
  if p_erased<0 or p_erased>p_total_keys then raise exception 'Invalid erased count'; end if;
  if p_errors<0 or p_errors>p_total_keys then raise exception 'Invalid error count'; end if;
  if p_duration_ms<greatest(250,p_words*120) or p_duration_ms>1800000 then raise exception 'Invalid round duration'; end if;
  if p_duration_ms>server_elapsed+5000 then raise exception 'Round duration does not match server timing'; end if;

  update public.round_challenges
  set status='consumed',consumed_at=now()
  where id=ch.id;

  insert into public.round_results(
    id,user_id,mode,score,words,erased,max_streak,total_keys,errors,duration_ms,
    one_clue_finish,challenge_id,verified,server_elapsed_ms
  )
  values(
    p_round,p_user,p_mode,p_score,p_words,p_erased,p_max_streak,p_total_keys,p_errors,p_duration_ms,
    p_one_clue,ch.id,true,server_elapsed
  );

  select * into s from public.player_stats where user_id=p_user for update;
  new_rounds:=s.rounds+1;
  new_words:=s.words+p_words;

  update public.player_stats set
    rounds=new_rounds,
    words=new_words,
    erased=s.erased+p_erased,
    best_score=greatest(s.best_score,p_score),
    verified_best_score=greatest(s.verified_best_score,p_score),
    verified_rounds=s.verified_rounds+1,
    best_streak=greatest(s.best_streak,p_max_streak),
    fastest_seconds=case
      when s.fastest_seconds is null then p_duration_ms/1000.0
      else least(s.fastest_seconds,p_duration_ms/1000.0)
    end,
    best_erased_round=greatest(s.best_erased_round,p_erased),
    mind_reader_count=s.mind_reader_count+(case when p_one_clue then 1 else 0 end),
    perfect_rounds=s.perfect_rounds+(case when p_errors=0 then 1 else 0 end),
    total_keys=s.total_keys+p_total_keys,
    total_errors=s.total_errors+p_errors,
    total_score=s.total_score+p_score,
    updated_at=now()
  where user_id=p_user
  returning * into s;

  if p_errors=0 then reward_coins:=reward_coins+10; end if;
  if p_max_streak>=5 then reward_coins:=reward_coins+5; end if;
  if p_mode='daily' then reward_coins:=reward_coins+15; end if;
  if new_rounds % 10=0 then reward_tickets:=1; end if;

  foreach ach in array array['mindReader','backspaceWarrior','perfectRead','marathon','century','comboKing'] loop
    if (ach='mindReader' and p_one_clue)
       or (ach='backspaceWarrior' and p_erased>=50)
       or (ach='perfectRead' and p_errors=0)
       or (ach='marathon' and new_rounds>=25)
       or (ach='century' and new_words>=100)
       or (ach='comboKing' and p_max_streak>=10) then
      insert into public.user_achievements(user_id,achievement_id)
      values(p_user,ach) on conflict do nothing;
      get diagnostics inserted_count=row_count;
      if inserted_count>0 then
        unlocked:=array_append(unlocked,ach);
        reward_coins:=reward_coins+75;
      end if;
    end if;
  end loop;

  if 'mindReader'=any(unlocked) then
    insert into public.inventory(user_id,item_id,source)
    values(p_user,'title_mindreader','achievement')
    on conflict do nothing;
  end if;

  select * into w from public.autotype_wallet_credit_coins(p_user,reward_coins);

  update public.wallets
  set tournament_tickets=tournament_tickets+reward_tickets,updated_at=now()
  where user_id=p_user
  returning * into w;

  if ch.tournament_id is not null then
    update public.tournament_entries
    set score=p_score,status='finished',finished_at=now()
    where tournament_id=ch.tournament_id and user_id=p_user;
  end if;

  insert into public.economy_transactions(
    user_id,kind,coins_delta,tickets_delta,metadata
  )
  values(
    p_user,'round_reward',reward_coins,reward_tickets,
    jsonb_build_object(
      'round_id',p_round,'mode',p_mode,'challenge_id',ch.id,
      'verified',true,'tournament_id',ch.tournament_id
    )
  );

  return jsonb_build_object(
    'duplicate',false,
    'verified',true,
    'stats',to_jsonb(s),
    'wallet',to_jsonb(w),
    'coins_earned',reward_coins,
    'tickets_earned',reward_tickets,
    'new_achievements',to_jsonb(unlocked),
    'server_elapsed_ms',server_elapsed
  );
end;
$$;

revoke execute on function public.autotype_record_verified_round(
  uuid,uuid,uuid,text,bigint,integer,integer,integer,integer,integer,integer,boolean
) from public,anon,authenticated;
grant execute on function public.autotype_record_verified_round(
  uuid,uuid,uuid,text,bigint,integer,integer,integer,integer,integer,integer,boolean
) to service_role;

create or replace function public.autotype_claim_daily_first(p_user uuid,p_day date)
returns jsonb language plpgsql security definer set search_path=public
as $$
declare top_score bigint; mine bigint; w public.wallets%rowtype;
begin
  select max(score) into top_score
  from public.round_results
  where mode='daily' and verified=true and created_at::date=p_day;

  select max(score) into mine
  from public.round_results
  where mode='daily' and verified=true and user_id=p_user and created_at::date=p_day;

  if coalesce(mine,0)<=0 or mine is distinct from top_score then
    raise exception 'You are not currently #1 for that Daily Challenge';
  end if;

  insert into public.daily_reward_claims(user_id,day)
  values(p_user,p_day) on conflict do nothing;
  if not found then raise exception 'Daily #1 reward already claimed'; end if;

  select * into w from public.autotype_wallet_credit_coins(p_user,150);

  insert into public.economy_transactions(user_id,kind,coins_delta,metadata)
  values(p_user,'daily_first_reward',150,jsonb_build_object('day',p_day,'verified',true));

  return jsonb_build_object('wallet',to_jsonb(w),'reward',150);
end;
$$;
